DevOps.UI/Models/Organization.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DevOps.UI.Models
{
    public class Organization
    {
        public int OrganisationId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Nationality { get; set; }
        public string Type { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}

DevOps.UI/Controllers/OrganizationController.cs
using DevOps.Common;
using DevOps.UI.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http.Cors;
using System.Web.Mvc;

namespace DevOps.UI.Controllers
{
    [EnableCorsAttribute("*", "*", "*")]
    [RoleAuth("Admin")]
    public class OrganizationController : Controller
    {
        [HttpGet]
        public ActionResult Registration()
        {
            return PartialView("Registration");
        }

        [HttpGet]
        public ActionResult Organization()
        {
            return PartialView("OrganizationTable");
        }

        [HttpGet]
        public async Task<ActionResult> EditOrganization(int id)
        {
            string token = Session["UserToken"].ToString();
            Organization organisations = new Organization();
            string address = "api/Organizations/GetOrganization?OrganisationId=" + id.ToString();
            HttpResponseMessage Res = await Helpers.Get(address, token);
            if (Res.IsSuccessStatusCode)
            {
                var MainMEnuResponse = Res.Content.ReadAsStringAsync().Result;
                organisations = JsonConvert.DeserializeObject<Organization>(MainMEnuResponse);
            }
            return PartialView(organisations);
        }   
    }
}

DevOps.UI/Views/Organization/EditOrganization.cshtml
@model DevOps.UI.Models.Organization
<div class="login-content">
   
    @using (Html.BeginForm())
    {
        <h2><center>Edit</center></h2>
        <div class="nk-block toggled" id="l-register">
            <input type="hidden" id="id" name="id" value="@Model.OrganisationId" />
            <div class="nk-form rform">
                <div class="input-group">
                    <span class="input-group-addon nk-ic-st-pro"><i class="fas fa-user"></i></span>
                    <div class="nk-int-st">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <br />

                <div class="input-group">
                    <span class="input-group-addon nk-ic-st-pro"><i class="fas fa-map-marker-alt"></i></span>
                    <div class="nk-int-st">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <br />


                <div class="input-group">
                    <span class="input-group-addon nk-ic-st-pro"><i class="fas fa-flag"></i></span>
                    <div class="nk-int-st">
                        @Html.EditorFor(model => model.Nationality, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <br />

                <div class="input-group">
                    <span class="input-group-addon nk-ic-st-pro"><i class="fas fa-mobile-alt"></i></span>
                    <div class="nk-int-st">
                        @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <br />
                <input type="submit" id="editbtn" value="Submit" class=" btn-success uloginbtn" />

                <a href="#l-login" data-ma-action="nk-login-switch" data-ma-block="#l-login" class="btn btn-login btn-success btn-float"><i class="notika-icon notika-right-arrow"></i></a>
            </div>
        </div>
    }
</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $('#editbtn').click(function (e) {
        e.preventDefault();
        var id = $('#id').val();
        var name = $('#Name').val();
        var Address = $('#Address').val();
        var Nationality = $('#Nationality').val();
        var Type= $('#Type').val();
        
        var url1 = "http://localhost:60969/api/Organizations/UpdateOrganization";
        $.ajax({
            url: url1,
            type: 'POST',//type of posting the data
            data: '{OrganisationId: "' + id + '",Name: "' + name + '",Address: "' + Address + '",Nationality: "' + Nationality +
                '",Type: "' + Type+ 
        '"}',
            contentType: 'application/json',
            dataType: 'json',
            success: function (r) {
                var url2 = "http://localhost:57996/Organization/Organization"
                $.ajax({
                    url: url2,
                    type: 'GET',//type of posting the data
                    contentType: 'application/json',
                    dataType: 'html',
                    success: function (r) {
                        $("#partialbody").empty();
                        $("#partialbody").append(r);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        //what to do in error
                    }
                });
            },
            error: function (xhr, ajaxOptions, thrownError) {
                //what to do in error
                console.log(thrownError);
            }
        });

    });
</script>

DevOps.UI/Views/Organization/OrganizationTable.cshtml
@model IEnumerable<DevOps.UI.Models.Organization>

<!-- Data Table area Start-->
<div class="data-table-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="data-table-list">
                    <div class="basic-tb-hd">
                        <h4>Organizations</h4>

                        <a class="ajaxclass" href="/Organization/Registration">
                            <h4>
                                <i class="fa fa-plus"></i>     Add New
                            </h4>
                        </a>
                    </div>
                    <div class="table-responsive">

                        @*<a class="ajaxclass" href="/Organization/Registration"><h4>Add New</h4></a>*@
                        @*<table id="data-table-basic" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Address</th>
                                        <th>Nationality</th>
                                        <th>Type</th>
                                        <th>Action </th>
                                    </tr>
                                </thead>
                                <tbody id="databody">
                                </tbody>

                            </table>*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="script">
</div>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        
        $.ajax({
            url: "http://localhost:60969/api/Organizations/GetAllOrganization",
            context: document.body,
            success: function (data) {
                $('#data-table-basic_wrapper').remove();
                var tbl = "<table id='data-table-basic' class='table table-striped'><thead><tr><th>Name</th><th>Address</th><th>Nationality</th><th>Type</th><th>Action</th></tr></thead><tbody></tbody></table>";
                $('.table-responsive').append(tbl);

                //$("#databody").empty();
                for (var i = 0, li = data.length; i < li; i++) {

                    var newTr = "<tr> <td>" + data[i].name + " </td><td>" + data[i].address + "</td><td>" + data[i].nationality + "</td><td>" + data[i].type + "</td><td> <input type='hidden' value=" + data[i].organisationId + ">";
                    if ('@Session["Role"].ToString()' == "Admin") {
                        newTr += "<a class='editajax' id='" + data[i].organisationId + "' href='#'>Edit</a> <a class='deleteajax' id='" + data[i].organisationId + "' href='#'>Delete</a>";
                    }
                    newTr += "</td></tr >";
                    $("#data-table-basic").append(newTr);
                    if ('@Session["Role"].ToString()' == "Admin") {
                        document.getElementsByClassName("editajax")[i].addEventListener("click", function (event) {
                            event.preventDefault();
                            var url1 = "http://localhost:57996/Organization/EditOrganization/" + event.target.id;
                            $.ajax({
                                url: url1,
                                type: 'GET',//type of posting the data
                                contentType: 'application/json',
                                dataType: 'html',
                                success: function (r) {
                                    //console.log(r.ViewString);
                                    $("#partialbody").empty();
                                    $("#partialbody").html(r);
                                },
                                error: function (xhr, ajaxOptions, thrownError) {
                                    //what to do in error
                                    alert(url1);
                                }
                            });

                        });
                        document.getElementsByClassName("deleteajax")[i].addEventListener("click", function (event) {
                            event.preventDefault();
                            if (confirm("Are you Sure Want to delete?")) {
                                var id = event.target.id;
                                var url1 = "http://localhost:60969/api/Organizations/DeleteOrganization/" + id;
                                $.ajax({
                                    url: url1,
                                    type: 'POST',//type of posting the data
                                    data: '{id: "' + id + '"}',
                                    dataType: 'json',
                                    success: function (r) {
                                        var url2 = "http://localhost:57996/Organization/Organization"
                                        $.ajax({
                                            url: url2,
                                            type: 'GET',//type of posting the data
                                            contentType: 'application/json',
                                            dataType: 'html',
                                            success: function (r) {
                                                $("#partialbody").empty();
                                                $("#partialbody").append(r);
                                            },
                                            error: function (xhr, ajaxOptions, thrownError) {
                                                //what to do in error
                                            }
                                        });
                                    },
                                    error: function (xhr, ajaxOptions, thrownError) {
                                        //what to do in error
                                        alert(thrownError);
                                    }
                                });
                            }
                        });
                    }
                }
                reload_js();

            }
        });

        function reload_js() {
            var s = "<script src='/Scripts/js/data-table/jquery.dataTables.min.js'><\/script>";
            s += "<script src='/Scripts/js/data-table/data-table-act.js'><\/script>";
            $('#script').append(s);
        };


        $('.ajaxclass').click(function (e) {
            e.preventDefault();
            //var id = window.location.href.split('/').pop(-1);
            //var url1 = "/Customers/Index";
            $.ajax({
                url: $(this).attr("href"),
                type: 'GET',//type of posting the data
                contentType: 'application/json',
                dataType: 'html',
                success: function (r) {
                    $("#partialbody").empty();
                    $("#partialbody").html(r);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    //what to do in error
                }
            });

        });
    });

</script>

DevOps.UI/Views/Organization/Registration.cshtml
@model DevOps.UI.Models.Organization
    @{
        Layout = null;
    }
    <div class="login-content">
        <!-- Login -->
        @using (Html.BeginForm("Registration", "Organization", FormMethod.Post))
        {
            <h2><center>Registration</center></h2>
            <div class="nk-block toggled" id="l-register">
                <div class="nk-form rform">
                    <div class="input-group">
                        <span class="input-group-addon nk-ic-st-pro"><i class="fas fa-user"></i></span>
                        <div class="nk-int-st">
                            <input type="text" id="Name" class="form-control" placeholder="Name" name="Name">
                        </div>
                    </div>
                    <br />

                    <div class="input-group">
                        <span class="input-group-addon nk-ic-st-pro"><i class="fas fa-map-marker-alt"></i></span>
                        <div class="nk-int-st">
                            <input type="text" id="Address" class="form-control" placeholder="Address" name="Address">
                        </div>
                    </div>
                    <br />

                    <div class="input-group">
                        <span class="input-group-addon nk-ic-st-pro"><i class="fas fa-map-marker-alt"></i></span>
                        <div class="nk-int-st">
                            <input type="text" id="Nationality" class="form-control" placeholder="Nationality" name="Nationality">
                        </div>
                    </div>
                    <br />

                    <div class="input-group">
                        <span class="input-group-addon nk-ic-st-pro"><i class="fas fa-flag"></i></span>
                        <div class="nk-int-st">
                            <input type="text" id="Type" class="form-control" placeholder="Type Of your Organization" name="Type">
                        </div>
                    </div>
                    <br />

                    <br /><br />
                    <input type="submit" id="submit" value="Submit" class=" btn-success uloginbtn" />
                    <a href="#l-login" data-ma-action="nk-login-switch" data-ma-block="#l-login" class="btn btn-login btn-success btn-float"><i class="notika-icon notika-right-arrow"></i></a>
                </div>
            </div>
        }
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script>
        $('#submit').click(function (e) {
            e.preventDefault();
            var name = $('#Name').val();
            var Address = $('#Address').val();
            var Nationality = $('#Nationality').val();
            var Type = $('#Type').val();
            var url1 = "http://localhost:60969/api/Organizations/InsertOrganization";
            $.ajax({
                url: url1,
                type: 'POST',//type of posting the data
                data: '{Name: "' + name + '",Address: "' + Address + '",Nationality: "' + Nationality + '",Type: "' + Type +
                    '"}',
                contentType: 'application/json',
                dataType: 'json',
                success: function (r) {
                    var url2 = "http://localhost:57996/Organization/Organization";
                    $.ajax({
                        url: url2,
                        type: 'GET',//type of posting the data
                        contentType: 'application/json',
                        dataType: 'html',
                        success: function (r) {
                            $("#partialbody").empty();
                            $("#partialbody").html(r);
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            //what to do in error
                        }
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    //what to do in error
                    console.log(thrownError);
                }
            });

        });
    </script>